### PR TITLE
Issue #1 Usage is unclear - Documentation addition

### LINKED ISSUE #1: Usage is unclear
The README is sorely lacking for info.
Because I'm not a total Rust noob, I reach for Cargo which told me to execute a command.  I guessed at `cargo build` which seemed to do the trick.  Unfortunately, that alone isn't enough to get going:

```
↳ target/debug/muxed
thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', ../src/libcollections/vec.rs:1134
```
I presume this is because I need to pass a commandline parameter?
(Sorry, haven't started looking at source yet - just trying to get my bearings first.)

### PR DESCRIPTION
**Pull request by brianp**
Add setup and usage instructions in the readme, as well as code docs throughout all modules.

Wouldn't mind a review from @GrooveStomp to help Resolve #1 .

Maybe give the setup instructions a go and see if you hit any problems?

### CODE REVIEW

**Comment by GrooveStomp** [comment]
The README is mostly good, but I'm missing *something*.
I've gone through all the steps up until the very last two.  The last two steps are ordered backwards compared to what someone new will expect, but that's not at all difficult to figure out.
However, building the project doesn't seem to work:
```
↳ cargo run project
   Compiling libc v0.2.10
   Compiling getopts v0.2.14
   Compiling yaml-rust v0.3.2
   Compiling rand v0.3.14
   Compiling muxed v0.2.0 (file:///home/aaron/code/muxed)
     Running `target/debug/muxed project`
thread '<main>' panicked at 'Config Read error: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:709
Process didn't exit successfully: `target/debug/muxed project` (exit code: 101)
```
And if I try without specifying `project` there:
```
↳ cargo run
     Running `target/debug/muxed`
thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', ../src/libcollections/vec.rs:1134
Process didn't exit successfully: `target/debug/muxed` (exit code: 101)
```

**Comment by brianp** [comment]
We're getting somewhere.

`cargo run` will always bail right now. (This is the fault tolerance I need to start looking at). It will bail because it's looking for a project to open. If we don't pass a project it has nothing to do.

`cargo run project` says to look for the `project.yml` in `~/.muxed/` which I believe it's finding but is claiming `Config Read error`.

So it's not having fun parsing the actual config. Is it the config copied from the setup sample? Or has there been changes?

Also,
Which two steps do you feel are mis-ordered. I think i left it a little ambiguous as to which way to compile. and maybe just need to suggest one way to compile and run. Instead of assuming someone know how to compile and then run the bin, or compile&run via cargo.

**Comment by GrooveStomp** [comment]
Ah. I see.  I followed the steps verbatim except instead of creating a `project.yml` file, I created `muxed-project.yml`.
I didn't even think that `cargo run project` was referring to the same project used in `project.yml`.  So `cargo run muxed-project` ought to work...

```
↳ cargo run muxed-project
     Running `target/debug/muxed muxed-project`
can't find window muxed_first_window_23817
sessions should be nested with care, unset $TMUX to force
```
Yep, that seems better!

I think the last two steps mentioned are ordered backwards for newbies.

> ### 4. Compile & run Muxed for your project.
> Here is where you call your project, with the same name as the config file created in step 2.
> 
> ```bash
> $ ./muxed project
> ```
> 
> #### With Cargo:
> 
> ```bash
> $ cargo run project
> ```

Won't you always be building with `cargo` first, then you can use the resulting executable to launch you project afterward, ala: `./muxed project` ?

**Comment by brianp** [comment]
I'll re-work the readme and try to make `project` have more meaning. And fixup the ambiguity in the last step. 

I noticed you got `can't find window muxed_first_window_23817`. Aside form the documentation issue did tmux actually open with your desired setup?

**Comment by GrooveStomp** [comment]
No.  I'll modify my config here a bit and see if I can make it work.

**Comment by GrooveStomp** [comment]
@brianp I modified my config file and ran from a fresh gnome-terminal (not already running tmux) and it worked.  My new config file looks like this:
```
rt: "~/"
windows:
  - editor:
      layout: "main-vertical"
      panes: ["jed", "tig"]
  - server: "~/code/asciiquarium/asciiquarium_1.1/asciiquarium"
  - logs: "tail -f /var/log/dmesg"
```
Not significantly different from the example one.  Perhaps it might be worthwhile to update the example one with some common programs anyone will have installed in a unixy environment and add a description of what to expect with that layout?

ie., perhaps:
```
rt: "~/"
windows:
  - editor:
      layout: "main-vertical"
      panes: ["vi", "ls -alh"]
  - processes: "ls /proc"
  - logs: "tail -f /var/log/dmesg"
```
```
This will create a new tmux session with three windows named *editor*, *processes* and *logs*.  By default your view will be on the last window opened, which in this case is *logs*.
The first window will have to panes split vertically, the left will have the editor *vi* running and the right will have a shell listing of your current working directory.  For more information on configuring *muxed* see X.

What does `rt: "~"` mean?

**Comment by brianp** [comment]
> What does rt: "~" mean?
`root: ~/` Defines the root directory windows open in.

I've made additional updates to the readme as per above discussion. 

Also the fact you had to have a "clean" tmux session in order to not get `can't find window muxed_first_window_23817` is a separate bug I've identified. Should be fixed soon.

**Comment by GrooveStomp** [comment]
Cool man. Well, that sorts it for the documentation I guess! :-)

**Comment by GrooveStomp** [comment]
That's a lot of in-code documentation. 
So... should I merge it?  It looks good to me.

**Pull request merged**
